### ISSUE TITLE
Samsung Internet: Grey box on Product Pages

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#508] opened 2021-08-27 15:03 UTC
**Describe the current behavior**

On Samsung Internet, on Android phones, there is a gray area above the first image of the product details page. 
![image](https://user-images.githubusercontent.com/8127145/131148396-337605fe-d18c-4fed-b59b-587e2e20d6df.png)

![image](https://user-images.githubusercontent.com/8127145/131148432-f9f13675-156f-404e-b4ba-d8df9ea9ac17.png)

From @martinamarien:

Seems like the issue is two-fold:
- the width and height attributes are not working properly on the image element.
- The padding we use for the image “placeholder” is not behind the image and/or not getting the right height.

**Comment by silkfab** [comment] 2021-08-28 15:38
this issue persists with some mobile browsers like Samsung, Vivo, and so many other mobile devices I checked it up.
and working fine with chrome, firefox, Mozilla, ie, etc.

It's a High Priority issue that affected all the team. plz, solve this as soon as possible.

**Comment by silkfab** [comment] 2021-08-29 10:21
After update the given code there are one more issue still presist in banner image... that is not responsive 
![Uploading Screenshot_20210829-154617_Samsung Internet.jpg…]()

**Comment by silkfab** [comment] 2021-08-29 11:03
.media__wrapper > img {
  display: block;
  max-width: 100%;
  height: 100%;
  width: 100%;
  position: relative;
}

change with 
.media__wrapper > img {
  display: block;
  max-width: 100%;
  height: 100%;
  width: 100%;
  position: absolute;
}

Now Working Fine

**Comment by kmeleta** [comment] 2021-09-02 15:01
The root cause of this issue was found and fixed via #311

**Closed by kmeleta** 2021-09-02 15:01 UTC
Labels: Severity: 1, bug, nice to have
