### ISSUE TITLE
[Theme settings - Drawers] Add color picker to drawer theme settings

### ISSUE THREAD

**Issue by Oliviammarcello** [Shopify/dawn#1611] opened 2022-04-11 16:30 UTC
Add color scheme picker to the `Drawers` `Theme settings`. [Figma](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=13991%3A100289)

**Comment by nicklepine** [comment] 2022-04-26 12:03
Duplicate of #1403.  closing.

**Closed by nicklepine** 2022-04-26 12:03 UTC
