### ISSUE TITLE
Image banner follow ups

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#959] opened 2021-12-02 18:21 UTC
**Describe the enhancement you'd like**

- [ ] **Add caption block (like image with text)**

Design: https://www.figma.com/file/igRnZQceCieIPmM3NYZJyC?node-id=102:29#129939476

Context: https://github.com/Shopify/dawn/pull/900#discussion_r760332045

- [ ] **Add opacity range for mobile**

Design: https://www.figma.com/file/igRnZQceCieIPmM3NYZJyC?node-id=306:3475#129935054

Context: https://github.com/Shopify/dawn/pull/900#discussion_r760551298
Related issue: #1327

~- [ ] **Update mobile content**~

~Context: https://github.com/Shopify/dawn/pull/900#discussion_r757633779~

Update: https://github.com/Shopify/dawn/pull/900#discussion_r761515471

cc @wiktoriaswiecicka @katycobb @melissaperreault

**Comment by sofiamatulis** [comment] 2021-12-02 18:22
Also there is the conversation of maybe adding a vertical alignment setting for mobile: https://github.com/Shopify/dawn/pull/900#discussion_r760537039

**Comment by katycobb** [comment] 2021-12-02 22:53
Hi @sofiamatulis, I reviewed the settings using the editor link in issue 900. I think everything I caught is captured above. One addition: Since we're adding the mobile opacity range, I've adjusted the existing opacity label to say "Desktop image overlay opacity" to clearly differentiate between the two.

**Comment by sofiamatulis** [comment] 2021-12-09 15:40
_For image banner, we'd like to add help text under the Desktop content position field to explain how this behaves on mobile: Position is automatically optimized for mobile._

Original comment by @katycobb https://github.com/Shopify/dawn/pull/990#issuecomment-989295772

**Comment by Stephanie-Chou** [comment] 2023-06-15 18:10
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps

**Closed by Stephanie-Chou** 2023-06-15 18:10 UTC
