### ISSUE TITLE
Is it possible to set the header menu in this way in the Shopify Dawn theme? Please help me

### ISSUE THREAD

**Issue by dinukadwc** [Shopify/dawn#1993] opened 2022-09-28 17:38 UTC
![CUSTOM MENU-01](https://user-images.githubusercontent.com/85406685/192850764-e1c1efd7-44ea-479d-be8f-059fc1082fd8.jpg)

Is it possible to set the header menu in this way in the Shopify Dawn theme? Please help me

**Comment by kimberlyoleiro** [comment] 2022-11-22 16:08
Can you please add more information regarding the requirements you're asking for here? this image shows two logos

**Comment by kimberlyoleiro** [comment] 2023-05-18 18:29
We appreciate you taking the time to report this issue. Unfortunately, we cannot reproduce it in the latest version of our codebase. We'll be closing this issue, but please let us know if you have any other feedback.

**Closed by kimberlyoleiro** 2023-05-18 18:29 UTC
Labels: enhancement, Critical Path: 3
