### ISSUE TITLE
Search results page title wrong count

### ISSUE THREAD

**Issue by pinguluk** [Shopify/dawn#1465] opened 2022-03-08 11:47 UTC
**Describe the current behavior**
![Screenshot_410](https://user-images.githubusercontent.com/16257821/157232036-0e5a4bbd-ccd1-4f8d-bfa0-5ec15ce9dd71.png)

**Describe the expected behavior**
Search results page title to have the correct count of products

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.4.0
- Chrome Version 99.0.4844.51
- Windows 21H1

**Possible solution**
...

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
...

**Comment by shawnr42** [comment] 2022-03-08 19:56
This seems like a duplicate of Issue 1030 - https://github.com/Shopify/dawn/issues/1030

**Comment by melissaperreault** [comment] 2022-10-26 03:06
Closing since this is a duplicate, thanks!
I think the issue no longer persist too.

**Closed by melissaperreault** 2022-10-26 03:06 UTC
