### ISSUE TITLE
Why isn't templates under “customers” directory to be JSON yet?

### ISSUE THREAD

**Issue by kogai** [Shopify/dawn#654] opened 2021-09-20 08:03 UTC
**Describe the enhancement you'd like**

JSON-templates are one of the most amazing feature revealed as the Online Store 2.0, I believe.

On the other hand, it seems that there are still a few important pages in Dawn that do not support JSON-templates yet.

If, for example, customers/login.liquid were JSON-templated, a social-login apps developers would be able to benefit from JSON templates, wouldn't this be great?

**Describe alternatives you've considered**

I've already [discussed abouit this with the community](https://community.shopify.com/c/online-store-2-0/why-templates-which-under-customers-of-dawn-doesn-t-json-format/m-p/1233825#M1058), and there doesn't seem to be any technical reason to prevent make Liquid-template files under the customers directory into JSON templates.

So, I think simply convert the Liqud-template files under the customers directory into a JSON one would be resolve the problem.

**Additional context/screenshots**

None.

Thanks.

**Comment by gregjotau** [comment] 2021-10-20 17:47
@tyleralsbury @ludoboludo I vote for this one if it is that easy 💪

**Comment by tyleralsbury** [comment] 2021-10-20 18:17
Duplicate of https://github.com/Shopify/dawn/issues/543

It's definitely on our radar.

**Closed by tyleralsbury** 2021-10-20 18:17 UTC
