### ISSUE TITLE
Cart drawer continue shopping button - change to editable button/link

### ISSUE THREAD

**Issue by ludoboludo** [Shopify/dawn#1661] opened 2022-05-04 18:12 UTC
**Describe the enhancement you'd like**
Currently when the cart drawer is empty you get a `continue shopping` button that links back to the collections/all.
This approach might not be the best, as this link might not be the desired place to send your visitors. 

We could give control to the merchant and add some setting options where they could edit the label and the link. As well as remove the label to remove the button itself. 

**Describe alternatives you've considered**
The alternative right now will be asking theme support to make the change for merchant but that will put them off the upgrade path.

We could also get rid of the button. Since there is the option to link a collection already, we might not need this collection link at all. 

**Additional context/screenshots**
![](https://screenshot.click/04-07-10kt9-vmcgr.png)

**Comment by Oliviammarcello** [comment] 2022-05-12 17:53
Good call out. I agree that this could be a choice. Since merchants can pick a collection separately, I wonder if `Continue shopping` just be offered as a checkbox?

**Comment by Stephanie-Chou** [comment] 2023-06-15 17:42
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps

**Closed by Stephanie-Chou** 2023-06-15 17:42 UTC
