### ISSUE TITLE
Some legacy browser versions don't support multiple selectors inside not() psuedo class

### ISSUE THREAD

**Issue by pjhardie** [Shopify/dawn#592] opened 2021-09-08 18:11 UTC
**Describe the current behavior**
On certain older browser version (e.g. chrome v. 87 and before) the negation psuedo selector only supports one argument. Unfortunately, it so happens that the one place in the theme files that we're using multiple selectors inside the not() psuedo class is the css that powers almost all image layout on the site! As a result, browsing the site on chrome v87 and before (and probably some other older browser versions) causes sever layout issues.

**Describe the expected behavior**
Image layout should still function even on versions of chrome before 87. 

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2
- Chrome Version 87
- macOS

**Possible solution**
Fortunately, I think this is a very simple fix since it's only one line of code that's causing the issue. 

If we change 

`.media > *:not(.zoom, .deferred-media__poster-button),`

to 

`.media > *:not(.zoom):not(.deferred-media__poster-button),`

then I think we can fix this without adding a single line of code.

**Additional context/screenshots**

![Screenshot 2021-09-08 110936](https://user-images.githubusercontent.com/8458782/132562138-f6d05bdf-af82-4f9f-92eb-5c6d6105f6bf.jpg)

Add any other context about the problem here. If applicable, add screenshots to help explain.
I know that we are committed to limiting support for older browsers but this feels like the compromise is worth it.

**Comment by tyleralsbury** [comment] 2021-09-10 17:06
cc @kmeleta @ludoboludo  I believe this issue is a duplicate of https://github.com/Shopify/dawn/issues/303 which was fixed in https://github.com/Shopify/dawn/pull/311

Can y'all confirm?

**Closed as completed** 2021-09-10 17:52 UTC

**Comment by tyleralsbury** [comment] 2021-09-10 18:10
Cool, thanks @pjhardie .
