### ISSUE TITLE
Predictive search does not fail gracefully with unsupported primary locales

### ISSUE THREAD

**Issue by cbothner** [Shopify/dawn#1375] opened 2022-02-18 17:45 UTC
The spinner just hangs.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/4642599/154735013-e115fbfb-86df-4a38-97c1-2ed71985b636.png">

**Comment by nicklepine** [comment] 2022-02-23 16:54
Duplicate of #1298

**Closed by nicklepine** 2022-02-23 16:54 UTC
Labels: Severity: 3, bug
