### ISSUE TITLE
[Section Headings] Introduce new flexible settings

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#1181] opened 2022-01-13 17:53 UTC
Impacts all sections with headings: 
- [ ] Featured Collection
- [ ] Collection List
- [ ] Multi Column
- [ ] Video
- [ ] Collage
- [ ] Blog Posts
- [ ] Page
- [ ] Tabs

[Internal Figma Link](https://www.figma.com/file/JcYdswrk2JhqBTGBVWPM7J/Dawn-2.0?node-id=15199%3A87022)

**WHAT'S NEW**

- [ ] Heading Size
- [ ] Heading Alignment
- [ ] Heading Horizontal Offset
- [ ] Heading Vertical Offset

![image](https://user-images.githubusercontent.com/8127145/149382876-f990c3c2-a2fe-4ff5-951e-eea4e9148749.png)
![image](https://user-images.githubusercontent.com/8127145/149383063-e95fbbd2-4a54-4146-8242-7661020096a1.png)

**Comment by martinamarien** [comment] 2022-02-10 03:13
I've decided to separate this into separate PRs. I think that these can be tackled and shipped separately. Heading size and alignment provide its own value to merchants, separate from the heading offset feature. 
- [ ] Heading size and alignment
- [ ] Heading offset
  * I'd like to spend some more time exploring this one and possibly refactor how we currently approach heading spacing.

**Comment by Stephanie-Chou** [comment] 2023-06-15 17:36
We are closing this issue. This issue was reported 2 years ago on an old version of Dawn. If this is still a high priority issue today, please re open with updated reproduction steps


also looks like some work on this was done. Plus with flex sections coming up- we may have new and better solutions

**Closed by Stephanie-Chou** 2023-06-15 17:36 UTC
Labels: Severity: 2, 🎨 Design
