### ISSUE TITLE
Filtering products extremely slow or not working at all.

### ISSUE THREAD

**Issue by OnCrud** [Shopify/dawn#330] opened 2021-08-05 18:31 UTC
**Describe the current behavior**
When filtering products on a collection page, the filters are running extremely slow or not at all. Currently only tested using a "colour" option within products.

**Describe the expected behavior**
To filter products by "colour" within a reasonable time.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0

- Chrome Version 92.0.4515.131
- macOS Version 10.14.6

-Safari Mobile
-iOS14.6

**Possible solution**
N/A

**Additional context/screenshots**
![67881](https://user-images.githubusercontent.com/63202858/128403252-3bad988e-cca9-4714-8005-0eb0e620e2e7.jpg)

**Comment by kimberlyoleiro** [comment] 2023-05-18 16:38
hi there, I cannot reproduce this issue on dawn v9. I'm going to close this ticket for now but please flag if you have further concerns

**Closed by kimberlyoleiro** 2023-05-18 16:38 UTC
