### ISSUE TITLE
CSS color rgb variables are not working in the proxy page 

### ISSUE THREAD

**Issue by devShubhamSharma** [Shopify/dawn#220] opened 2021-07-19 07:09 UTC
**Describe the current behavior**
 1. --color-base-accent-1 :  {{ settings.colors_accent_1.red }}, {{ settings.colors_accent_1.green }}, {{ settings.colors_accent_1.blue }};
 
 This code is working in the main url, but not in the Proxy Page on the proxy page we can not find rgb value.See the attached screenshots 1.

**Describe the expected behavior**

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.1.0
- Chrome Version 91.0.4472.114

**Possible solution**
Add the color filter like below

 --color-base-accent-1: {{ settings.colors_accent_1 | color_extract: 'red' }}, {{ settings.colors_accent_1 | color_extract: 'green' }}, {{ settings.colors_accent_1 | color_extract: 'blue' }};

It's working on main pages and proxy pages both see the attached screenshot 2.

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

1. ![image](https://user-images.githubusercontent.com/61183439/126116711-1c897eaf-3229-41d9-9689-44062c3980bd.png)

![image](https://user-images.githubusercontent.com/61183439/126117149-9db2b2c3-5e86-4fc8-a866-60133d70b370.png)

2. 
![image](https://user-images.githubusercontent.com/61183439/126117508-3f61b113-60b7-4097-a9aa-d9fefeaff48d.png)

![image](https://user-images.githubusercontent.com/61183439/126117541-d73cd32a-6388-4e05-9008-693d16b2722f.png)

**Comment by neha-thakur-shopify** [comment] 2022-03-28 20:35
We are closing this issue as we were not able to reproduce it.

Feel free to open another issue in case you encounter something similar.

**Closed by neha-thakur-shopify** 2022-03-28 20:35 UTC
