### ISSUE TITLE
Price Range filter change to the range Slider

### ISSUE THREAD

**Issue by BoskiMehta** [Shopify/dawn#302] opened 2021-08-03 12:29 UTC
Hi
Please add the price range slider feature in collection filters
Please this https://i.imgur.com/hSxpRxO.png
Because it's more user friendly than to enter the price 

Thanks in advance

**Comment by nicklepine** [comment] 2021-08-03 12:51
Hi @BoskiMehta ! I will close this ticket since it is a duplicate of #44 . I'll comment your reference on that ticket.

This is an iteration we plan on making in the near future.

**Closed by nicklepine** 2021-08-03 12:51 UTC
