### ISSUE TITLE
Blog Posts Section: Liquid Error when Blog is deleted

### ISSUE THREAD

**Issue by nicklepine** [Shopify/dawn#11] opened 2021-06-25 14:32 UTC
![image](https://user-images.githubusercontent.com/8127145/123440245-936fe680-d5a0-11eb-99a6-e59ec58dd666.png)

**Problem**
When a blog gets deleted, but was referenced in a section on the theme, the theme throws this error:
Dawn Liquid error: sections/feature-blog.liquid:17 : Comparison of Integer with String failed

**Steps**
Create a blog
In theme editor, add blogpost section and select newly created blog. save.
Go and delete that blog.
Back in the editor, observe section serving this error.

Is there a more graceful failure we could output?

**Comment by melissaperreault** [comment] 2022-12-22 04:42
Closing since I can no longer reproduce. I will follow up though because the Blog setting should visually represent that the linked blog no longer exist and prompt merchants to an action to fix it. Or at least recognize there is a mistake.

**Closed by melissaperreault** 2022-12-22 04:42 UTC
Labels: Severity: 3, bug
