### ISSUE TITLE
Rounded corners on Slideshow

### ISSUE THREAD

**Issue by YoannJailin** [Shopify/dawn#1732] opened 2022-05-24 14:38 UTC
When using the slideshow section, there is a setting call "on grid". 
If i use rounded corners on the media settings, i am expecting rounded corners around the section when it's on grid. Currently, it doesn't works like that and stays angular.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 5.0.0
- Chrome Version Version 101.0.4951.64
- macOS Version 12.3.1

Possible solution : set rounded corners on the slideshow section, according to the media setting.

<img width="1476" alt="Capture d’écran, le 2022-05-24 à 10 37 19" src="https://user-images.githubusercontent.com/95925370/170062452-4f082777-9715-4fc1-9a0c-1dcb4e6c015d.png">

**Comment by nicklepine** [comment] 2022-05-24 14:54
Closing. It's a duplicate of #1068

**Closed as completed by nicklepine** 2022-05-24 14:54 UTC
