### ISSUE TITLE
[Video] Missing rounded corners

### ISSUE THREAD

**Issue by svinkle** [Shopify/dawn#1126] opened 2022-01-07 19:01 UTC
**Describe the current behavior**
Video section `button` and `iframe` elements are missing rounded corners when set on the theme.

**Describe the expected behavior**
Corners to be rounded.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 2.5.0
- Firefox 95 (any browser)
- macOS Version 12.1

**Possible solution**
Apply the `Media corder radius` setting value to the `border-radious` property of the `button` and `iframe` elements.

**Additional context/screenshots**
<img width="339" alt="" src="https://user-images.githubusercontent.com/1392632/148593517-95fe8e27-52f7-46cf-bc35-96c21796068b.png">
<img width="309" alt="" src="https://user-images.githubusercontent.com/1392632/148593518-3d8a3c81-e744-4109-bebf-9b5019c858f4.png">

**Comment by nicklepine** [comment] 2022-01-07 19:37
I'm gonna close this.  Duplicate of #1117

**Closed** 2022-01-07 19:38 UTC
Labels: bug
