### ISSUE TITLE
Cart note scroll bar overflowing

### ISSUE THREAD

**Issue by sofiamatulis** [Shopify/dawn#1182] opened 2022-01-13 18:35 UTC
**Describe the current behavior**
The cart note scroll bar overflows when we have corner radius: [Image here](https://camo.githubusercontent.com/13c285ebab7ce67ccea42dd6adce9d6c5a0a2002e3d25cb8217ce880c3c4a143/68747470733a2f2f73637265656e73686f742e636c69636b2f32322d30312d706c6f79302d6a377063692e706e67
)

**Describe the expected behavior**
The scroll bar should not overflow

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**
From @kmeleta: `She can correct me if I'm wrong but I assume Martina's suggestion would be something along the lines of adding a new parent element around the <textarea> and applying the border radius stuff and an overflow: hidden to that instead. I have no problem recording this as an issue and handling as a follow up if everyone agrees this is probably more sev 2.`

**Additional context/screenshots**
Original comment: https://github.com/Shopify/dawn/pull/1097#discussion_r783429797

cc @martinamarien @ludoboludo

**Comment by nicklepine** [comment] 2022-02-04 14:58
Duplicate of #1305 . Closing

**Closed by nicklepine** 2022-02-04 14:58 UTC
