### ISSUE TITLE
[Global settings] Adjust adjacent borders and corners

### ISSUE THREAD

**Issue by melissaperreault** [Shopify/dawn#922] opened 2021-11-19 19:24 UTC
### Some considerations

- [ ]  Like other sections where there is 0 grip gap, logic needs to be added to ensure collapsing of adjacent borders + elimination of border-radius for adjacent corners. This it not yet implemented.
   - [ ] Product cards
   - [ ] Blog cards
   - [ ] Image with text
- [ ] This is also sometimes due to `Vertical spacing between sections` setting from `Layout` that could be set to 0
   - [ ] Image with text
   - [ ] ...TBD

**Comment by KaichenWang** [comment] 2021-11-22 15:01
I will explore behaviour of section child elements when `Vertical spacing between sections` is set to zero together with https://github.com/Shopify/dawn/issues/925

**Comment by tyleralsbury** [comment] 2021-12-01 20:49
> I will explore behaviour of section child elements when Vertical spacing between sections is set to zero together with #925

I see that this is from 9 days ago but I don't imagine that it will be easy to handle these cases.  Are we still considering it?  I would strongly advise against trying to create any logic like this.  If we did have section settings that corresponded to the entire section container, it would be different, but since it's elements within the section it's very sketchy.

**Comment by kmeleta** [comment] 2022-03-23 00:17
Opened a separate ticket to account for the section-specific collapsing work https://github.com/Shopify/dawn/issues/1524. This work is slightly different than the content collapsing within sections and I feel they can be handled and merged asynchronously.

**Comment by Stephanie-Chou** [comment] 2023-06-15 18:09
We are closing this issue. This issue was reported on an old version of Dawn (we are now on 10.0. If this is still a high priority issue today, please re open with updated reproduction steps

**Closed by Stephanie-Chou** 2023-06-15 18:09 UTC
Labels: Severity: 2, global settings
